services:
  - type: worker
    name: velocity-bingo-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd bot && python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: LOGGER_GROUP_ID
        sync: false
      - key: SUPPORT_CHANNEL
        sync: false
